server:
  port: 8090
spring:
  profiles: test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false

  datasource:
    url: jdbc:mysql://localhost:3306/pet_did?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver